---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-ingress-np
  namespace: jalapeno-collectors
spec:
  type: NodePort
  ports:
  - name: 57400-tcp
    port: 57400
    nodePort: 32400
    targetPort: 57400
  selector:
    app: telegraf-ingress

