apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-ingress-deployment
  namespace: jalapeno-collectors
  labels:
    app: telegraf-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-ingress
  template:
    metadata:
      labels:
        app: telegraf-ingress
    spec:
      containers:
        - name: telegraf
          image: telegraf:1.15-alpine
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-ingress-config
              subPath: telegraf.conf
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: telegraf-ingress-config
          configMap:
            name: telegraf-ingress-config
