package openbmp

var headers = map[string][]string{
	"openbmp.parsed.base_attribute": []string{"action", "sequence", "hash", "router_hash",
		"router_ip", "peer_hash", "peer_ip", "peer_asn",
		"timestamp", "origin", "as_path", "as_path_count",
		"origin_as", "nexthop", "med", "local_pref",
		"aggregator", "community_list", "ext_community_list",
		"cluster_list", "isatomicagg", "is_nexthop_ipv4", "originator_id",
	},

	"openbmp.parsed.bmp_stat": []string{"action", "sequence", "router_hash", "router_ip",
		"peer_hash", "peer_ip", "peer_asn", "timestamp", "rejected",
		"known_dup_updates", "known_dup_withdraws", "invalid_cluster_list",
		"invalid_as_path", "invalid_originator", "invalid_as_confed", "pre_policy",
		"post_policy"},

	"openbmp.parsed.collector": []string{
		"action", "sequence", "admin_id", "hash",
		"routers", "router_count", "timestamp",
	},

	"openbmp.parsed.l3vpn": []string{"action",
		"sequence",
		"hash",
		"router_hash",
		"router_ip",
		"base_attr_hash",
		"peer_hash",
		"peer_ip",
		"peer_asn",
		"timestamp",
		"prefix",
		"prefix_len",
		"is_ipv4",
		"origin",
		"as_path",
		"as_path_count",
		"origin_as",
		"nexthop",
		"med",
		"local_pref",
		"aggregator",
		"community_list",
		"ext_community_list",
		"cluster_list",
		"isatomicagg",
		"is_nexthop_ipv4",
		"originator_id",
		"path_id",
		"labels",
		"isprepolicy",
		"is_adj_rib_in",
		"vpn_rd",
		"vpn_rd_type"},

	"openbmp.parsed.ls_link": []string{
		"action", "sequence", "hash", "base_attr_hash", "router_hash",
		"router_ip", "peer_hash", "peer_ip", "peer_asn", "timestamp",
		"igp_router_id", "router_id", "routing_id", "ls_id", "ospf_area_id",
		"isis_area_id", "protocol", "as_path", "local_pref", "med",
		"nexthop", "mt_id", "local_link_id", "remote_link_id", "intf_ip",
		"nei_ip", "igp_metric", "admin_group", "max_link_bw", "max_resv_bw",
		"unresv_bw", "te_default_metric", "link_protection", "mpls_proto_mask",
		"srlg", "link_name",
		"remote_node_hash", "local_node_hash",
		"remote_igp_router_id", "remote_router_id",
		"local_node_asn", "remote_node_asn",
		"peer_node_sid", "isprepolicy", "is_adj_rib_in",
		"ls_adjacency_sid",
	},

	"openbmp.parsed.ls_node": []string{
		"action", "sequence", "hash", "base_attr_hash", "router_hash",
		"router_ip", "peer_hash", "peer_ip", "peer_asn", "timestamp",
		"igp_router_id", "router_id", "routing_id", "ls_id", "mt_id",
		"ospf_area_id", "isis_area_id", "protocol", "flags", "as_path",
		"local_pref", "med",
		"nexthop", "name",
		"isprepolicy", "is_adj_rib_in",
		"ls_sr_capabilities",
	},

	"openbmp.parsed.ls_prefix": []string{
		"action", "sequence", "hash", "base_attr_hash", "router_hash",
		"router_ip", "peer_hash", "peer_ip", "peer_asn", "timestamp",
		"igp_router_id", "router_id", "routing_id", "ls_id", "ospf_area_id",
		"isis_area_id", "protocol", "as_path", "local_pref", "med",
		"nexthop", "local_node_hash", "mt_id", "ospf_route_type", "igp_flags",
		"route_tag", "ext_route_tag", "ospf_fwd_addr", "igp_metric", "prefix",
		"prefix_len",
		"isprepolicy", "is_adj_rib_in",
		"ls_prefix_sid",
	},

	"openbmp.parsed.peer": []string{"action", "sequence", "hash", "router_hash", "name",
		"remote_bgp_id", "router_ip", "timestamp", "remote_asn",
		"remote_ip", "peer_rd", "remote_port", "local_asn",
		"local_ip", "local_port", "local_bgp_id", "info_data", "adv_cap",
		"recv_cap", "remote_holddown", "adv_holddown", "bmp_reason",
		"bgp_error_code", "bgp_error_sub_code", "error_text", "is_l",
		"isprepolicy", "is_ipv4",
		"is_locrib", "is_locrib_filtered", "table_name",
	},

	"openbmp.parsed.router": []string{"action", "sequence", "name", "hash", "ip_addr", 
                "description", "term_code", "term_reason", "init_data", "term_data",
		"timestamp", "bgp_id",
	},

	"openbmp.parsed.unicast_prefix": []string{
		"action", "sequence", "hash", "router_hash", "router_ip",
		"base_attr_hash", "peer_hash", "peer_ip", "peer_asn", "timestamp",
		"prefix", "prefix_len", "is_ipv4", "origin", "as_path",
		"as_path_count", "origin_as", "nexthop", "med", "local_pref",
		"aggregator", "community_list", "ext_community_list", "cluster_list", "isatomicagg",
		"is_nexthop_ipv4", "originator_id",
		"path_id", "labels",
		"isprepolicy", "is_adj_rib_in",
	},

	        "openbmp.parsed.evpn": []string{
		"action", "sequence", "hash", "router_hash", "router_ip",
		"base_attr_hash", "peer_hash", "peer_ip", "peer_asn", "timestamp",
		"origin", "as_path", "as_path_count", "origin_as", "nexthop", "med", "local_pref",
		"aggregator", "community_list", "ext_community_list", "cluster_list", "isatomicagg",
		"is_nexthop_ipv4", "originator_id", "path_id", "isprepolicy", "is_adj_rib_in", 
		"route_distinguisher", "route_distinguisher", "originating_rtr_ip_len", "originating_router_ip", 
		"ethernet_tag_id_hex", "ethernet_segment_id", "mac_len", "mac", "ip_len", "ip", 
		"mpls_label_1", "mpls_label_2",
	},
}
