# coding: utf-8

"""
    Voltron Framework

    This outlines version 1 of the voltron framework API. 

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import client
from client.rest import ApiException
from client.models.edge_score import EdgeScore


class TestEdgeScore(unittest.TestCase):
    """ EdgeScore unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdgeScore(self):
        """
        Test EdgeScore
        """
        model = client.models.edge_score.EdgeScore()


if __name__ == '__main__':
    unittest.main()
