---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: arangodb
spec:
  capacity:
       storage: 50Gi
  accessModes:
       - ReadWriteMany
  nfs:
    path: /export/arangodb
    server: {{ host_ip }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: arangodb-apps
spec:
  capacity:
       storage: 10Gi
  accessModes:
       - ReadWriteMany
  nfs:
    path: /export/arangodb-apps
    server: {{ host_ip }}
  persistentVolumeReclaimPolicy: Retain
