# coding: utf-8

"""
    Voltron Framework

    This outlines version 1 of the voltron framework API. 

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import client
from client.rest import ApiException
from client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_add_collector(self):
        """
        Test case for add_collector

        
        """
        pass

    def test_delete_collector(self):
        """
        Test case for delete_collector

        
        """
        pass

    def test_get_collector(self):
        """
        Test case for get_collector

        
        """
        pass

    def test_get_collectors(self):
        """
        Test case for get_collectors

        
        """
        pass

    def test_get_healthz(self):
        """
        Test case for get_healthz

        
        """
        pass

    def test_get_liveness(self):
        """
        Test case for get_liveness

        
        """
        pass

    def test_get_metrics(self):
        """
        Test case for get_metrics

        
        """
        pass

    def test_heartbeat_collector(self):
        """
        Test case for heartbeat_collector

        
        """
        pass

    def test_update_collector(self):
        """
        Test case for update_collector

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
