# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "1.0"
  title: Voltron Framework
  description: |
    This outlines version 1 of the voltron framework API.

basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
  Basic:
    type: basic

security:
  - Bearer: []

parameters:
  collector-name:
    name: collector-name
    in: path
    type: string
    required: true
  responder-name:
    name: responder-name
    in: path
    type: string
    required: true

# Describe your paths here
paths:
  /collectors:
    get:
      description: get all collector services
      operationId: getCollectors
      responses:
        200:
          description: the fetched collectors
          schema:
            type: array
            items:
              $ref: '#/definitions/Collector'
    post:
      description: inserts new collector
      operationId: addCollector
      parameters:
        - in: body
          name: body
          description: Collector object
          required: true
          schema:
            title: addCollectorRequest
            $ref: "#/definitions/Collector"
      responses:
        201:
          description: created
          headers:
            newUrl:
              description: /collectors/<new-site-name>
              type: string
        400:
          description: Invalid Collector input

  /collectors/{collector-name}:
    get:
     parameters:
         - $ref: '#/parameters/collector-name'
     description: get collector by name
     operationId: getCollector
     responses:
       200:
         description: the fetched collector
         schema:
          title: getCollectorRequest
          $ref: '#/definitions/Collector'
    post:
     description: updates collector
     operationId: updateCollector
     parameters:
       - $ref: '#/parameters/collector-name'
       - in: body
         name: body
         description: Collector object
         required: true
         schema:
           title: updateCollectorRequest
           $ref: "#/definitions/Collector"
     responses:
       200:
         description: accepted
       400:
         description: Invalid Collector input
    delete:
     description: delete Collector by Name
     operationId: deleteCollector
     parameters:
       - $ref: '#/parameters/collector-name'
     responses:
       200:
         description: success
       404:
         description: collector not found
  /collectors/{collector-name}/heartbeat:
    get:
     parameters:
         - $ref: '#/parameters/collector-name'
     description: heartbeat endpoint for a specific collector
     operationId: heartbeatCollector
     responses:
       200:
         description: heartbeat collector
         schema:
          title: heartBeatCollector
          $ref: '#/definitions/Collector'
  /healthz:
    get:
      description: get health of framework
      operationId: getHealthz
      responses:
        200:
          description: healthy framework
        500:
          description: not healthy framework
  /liveness:
    get:
      description: get liveness of framework
      operationId: getLiveness
      responses:
        200:
          description: live of framework
        500:
          description: not live framework
  /metrics:
    get:
      description: lets prometheus scrape the framework
      operationId: getMetrics
      responses:
        200:
          description: Good metrics


definitions:
  Collector:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      status:
        type: string
        enum:
          - "Running"
          - "Down"
      edgeType:
        type: string
      fieldName:
        type: string
      fieldType:
        type: string
      timeout:
        type: string
      LastHeartbeat:
        type: string
