# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class D3Node(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, group: int=None):  # noqa: E501
        """D3Node - a model defined in Swagger

        :param id: The id of this D3Node.  # noqa: E501
        :type id: str
        :param group: The group of this D3Node.  # noqa: E501
        :type group: int
        """
        self.swagger_types = {
            'id': str,
            'group': int
        }

        self.attribute_map = {
            'id': 'id',
            'group': 'group'
        }

        self._id = id
        self._group = group

    @classmethod
    def from_dict(cls, dikt) -> 'D3Node':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The d3Node of this D3Node.  # noqa: E501
        :rtype: D3Node
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this D3Node.


        :return: The id of this D3Node.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this D3Node.


        :param id: The id of this D3Node.
        :type id: str
        """

        self._id = id

    @property
    def group(self) -> int:
        """Gets the group of this D3Node.


        :return: The group of this D3Node.
        :rtype: int
        """
        return self._group

    @group.setter
    def group(self, group: int):
        """Sets the group of this D3Node.


        :param group: The group of this D3Node.
        :type group: int
        """

        self._group = group
