REGISTRY_NAME?=docker.io/iejalapeno
IMAGE_VERSION?=latest

.PHONY: all api-gw-default-backend container push clean test

ifdef V
TESTARGS = -v -args -alsologtostderr -v 5
else
TESTARGS =
endif

all: api-gw-default-backend

api-gw-default-backend:
	mkdir -p bin
	$(MAKE) -C ./cmd/api-gw-default-backend compile-default-backend

container: api-gw-default-backend
	docker build -t $(REGISTRY_NAME)/api-gw-default-backend:$(IMAGE_VERSION) -f ./build/Dockerfile.api-gw-default-backend .

push: container
	docker push $(REGISTRY_NAME)/api-gw-default-backend:$(IMAGE_VERSION)

clean:
	rm -rf bin

test:
	GO111MODULE=on go test `go list ./... | grep -v 'vendor'` $(TESTARGS)
	GO111MODULE=on go vet `go list ./... | grep -v vendor`
