/*
 * Voltron Framework
 *
 * This outlines version 1 of the voltron framework API.
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

type Collector struct {
	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Status string `json:"status,omitempty"`

	EdgeType string `json:"edgeType,omitempty"`

	FieldName string `json:"fieldName,omitempty"`

	FieldType string `json:"fieldType,omitempty"`

	Timeout string `json:"timeout,omitempty"`

	LastHeartbeat string `json:"LastHeartbeat,omitempty"`
}
