---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lsv4_edge
  template:
    metadata:
      labels:
        app: lsv4_edge
    spec:
      containers:
        - args:
            - --v
            - "5"
            - --message-server
            - 'broker.jalapeno:9092'
            - --database-server
            - "http://arangodb.arangodb:8529"
            - --database-name
            - "jalapeno"
            - --database-user
            - "root"
            - --database-pass
            - "jalapeno"
          image: docker.io/sbezverk/lsv4_edge:wip
          imagePullPolicy: Always
          name: lsv4_edge
metadata:
  name: lsv4_edge
  namespace: default
