---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology
  template:
    metadata:
      labels:
        app: topology
    spec:
      containers:
        - args:
          - --v
          - "5"
          - --message-server
          - "broker.jalapeno:9092"
          - --database-server
          - "http://arangodb.jalapeno:8529"
          - --database-name
          - "jalapeno"
          - --database-user
          - "root"
          - --database-pass
          - "jalapeno"
          - --asn
          - '100000'
          image: docker.io/iejalapeno/gobmp-topology@sha256:5c7f7861d8d09260d8a06bfe3bf0e97b57ba65b64c6211e143d00edbc0269da0
          imagePullPolicy: Always
          name: topology
metadata:
  name: topology
  namespace: jalapeno
