---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology
  template:
    metadata:
      labels:
        app: topology
    spec:
      containers:
        - args:
          - --v
          - "5"
          - --message-server
          - "broker.jalapeno:9092"
          - --database-server
          - "http://arangodb.jalapeno:8529"
          - --database-name
          - "jalapeno"
          - --database-user
          - "root"
          - --database-pass
          - "jalapeno"
          - --asn
          - '100000'
          image: docker.io/iejalapeno/gobmp-topology@sha256:595467528247e3770b1b02c059934a30a675c66848d7b6c02d7eff4bd5db5e15
          imagePullPolicy: Always
          name: topology
metadata:
  name: topology
  namespace: jalapeno
