---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology1
  template:
    metadata:
      labels:
        app: topology1
    spec:
      containers:
        - args:
          - --v
          - "5"
          - --message-server
          - "broker.jalapeno:9092"
          - --database-server
          - "http://arangodb.jalapeno:8529"
          - --database-name
          - "jalapeno"
          - --database-user
          - "root"
          - --database-pass
          - "jalapeno"
          - --asn
          - '65000'
          image: docker.io/iejalapeno/gobmp-topology@sha256:d730614e6c62b02143862fe4cfb9ed889878e3ff2e31444215b4fc53a14aca58
          imagePullPolicy: Always
          name: topology1
metadata:
  name: topology1
  namespace: jalapeno
