---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology1
  template:
    metadata:
      labels:
        app: topology1
    spec:
      containers:
        - args:
          - --v
          - "5"
          - --message-server
          - "broker.jalapeno:9092"
          - --database-server
          - "http://arangodb.jalapeno:8529"
          - --database-name
          - "jalapeno"
          - --database-user
          - "root"
          - --database-pass
          - "jalapeno"
          - --asn
          - '65000'
          image: docker.io/iejalapeno/gobmp-topology@sha256:b50ed6563455788b6b053d4a379a3c19430a4c1262ae7bb654b4e768f7cd6308
          imagePullPolicy: Always
          name: topology1
metadata:
  name: topology1
  namespace: jalapeno
