apiVersion: v1
kind: ServiceAccount
metadata:
  name: jalapeno
  namespace: jalapeno 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jalapeno
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jalapeno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jalapeno
subjects:
  - kind: ServiceAccount
    name: jalapeno
    namespace: jalapeno
---
