{{- if and .Values.kafka.enabled .Values.kafka.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jalapeno.fullname" . }}-kafka
  labels:
    {{- include "jalapeno.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.kafka.persistence.size }}
{{- end }} 