{{- if .Values.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jalapeno.fullname" . }}-zookeeper
  labels:
    {{- include "jalapeno.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: 2181
      targetPort: client
      protocol: TCP
      name: client
    - port: 2888
      targetPort: follower
      protocol: TCP
      name: follower
    - port: 3888
      targetPort: leader
      protocol: TCP
      name: leader
  selector:
    {{- include "jalapeno.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
{{- end }} 