{{- if and .Values.grafana.enabled .Values.influxdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jalapeno-grafana-datasources
  labels:
    {{- include "jalapeno.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: grafana
type: Opaque
stringData:
  influxdb-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: InfluxDB
      type: influxdb
      access: proxy
      url: http://{{ .Release.Name }}-influxdb:{{ .Values.influxdb.service.port }}
      database: {{ .Values.influxdb.database }}
      user: {{ .Values.influxdb.auth.user.username }}
      secureJsonData:
        password: {{ .Values.influxdb.auth.user.password | default (randAlphaNum 10) }}
      isDefault: true
      editable: true
      jsonData:
        httpMode: GET
{{- end }} 