apiVersion: v1
kind: Service
metadata:
  name: jalapeno-api
  namespace: jalapeno
spec:
  type: NodePort
  selector:
    app: jalapeno-api
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30800 