apiVersion: apps/v1
kind: Deployment
metadata:
  name: jalapeno-api
  namespace: jalapeno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jalapeno-api
  template:
    metadata:
      labels:
        app: jalapeno-api
    spec:
      containers:
      - name: api
        image: iejalapeno/jalapeno-api:latest
        imagePullPolicy: Always
        env:
        - name: JALAPENO_DATABASE_SERVER
          value: "http://arangodb:8529"
        - name: JALAPENO_DATABASE_NAME
          value: "jalapeno"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
        volumeMounts:
          - name: credentials
            mountPath: /credentials
        ports:
        - containerPort: 8000
      volumes:
        - name: credentials
          secret:
            secretName: jalapeno 