apiVersion: v1
kind: Service
metadata:
  name: jalapeno-ui
  namespace: jalapeno
  labels:
    app: jalapeno-ui
  annotations:
    service.kubernetes.io/description: "Jalapeno UI service exposed on NodePort 30700"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30700
    protocol: TCP
    name: http
  selector:
    app: jalapeno-ui 