---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pvzoo
spec:
  capacity:
       storage: 10Gi
  accessModes:
       - ReadWriteMany
  nfs:
    path: /data/openshift-nfs/pvzoo
    server: 10.225.210.98
  persistentVolumeReclaimPolicy: Retain
