---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pvkafka
   labels:
      type: local
spec:
  capacity:
       storage: 50Gi
  accessModes:
       - ReadWriteOnce
  hostPath:
    path: /home/kube/pvkafka
