---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igp-graph
  template:
    metadata:
      labels:
        app: igp-graph
    spec:
      containers:
        - args:
            - --v
            - "5"
            - --message-server
            - "broker.jalapeno:9092"
            - --database-server
            - "http://arangodb.jalapeno:8529"
            - --database-name
            - "jalapeno"
          image: docker.io/iejalapeno/igp-graph:latest
          imagePullPolicy: Always
          name: igp-graph
          volumeMounts:
            - name: credentials
              mountPath: /credentials
      volumes:
        - name: credentials
          secret:
            secretName: jalapeno
metadata:
  name: igp-graph
  namespace: jalapeno
