/*
 * Voltron Framework
 *
 * This outlines version 1 of the voltron framework API.
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

type LinkEdge struct {
	Key string `json:"_key,omitempty"`

	From string `json:"_from,omitempty"`

	To string `json:"_to,omitempty"`

	FromIP string `json:"FromIP,omitempty"`

	ToIP string `json:"ToIP,omitempty"`

	Netmask string `json:"Netmask,omitempty"`

	Label string `json:"Label,omitempty"`

	V6 bool `json:"V6,omitempty"`
}
