/*
 * Voltron Framework
 *
 * This outlines version 1 of the voltron framework API.
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

type PrefixEdge struct {
	Key string `json:"_key,omitempty"`

	From string `json:"_from,omitempty"`

	To string `json:"_to,omitempty"`

	NextHop string `json:"NextHop,omitempty"`

	InterfaceIP string `json:"InterfaceIP,omitempty"`

	ASPath []string `json:"ASPath,omitempty"`

	Labels []string `json:"Labels,omitempty"`

	BGPPolicy string `json:"BGPPolicy,omitempty"`
}
