/*
 * Voltron Framework
 *
 * This outlines version 1 of the voltron framework API.
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

type Prefix struct {
	Key string `json:"_key,omitempty"`

	Prefix string `json:"Prefix,omitempty"`

	Length int32 `json:"Length,omitempty"`
}
