#!/usr/bin/env python
"""Configuration file for ArangoDB connections.
Specify the values according to environment.
"""

url = 'http://{{ arango_endpoint }}'
username = 'root'
password = 'jalapeno'
database = 'jalapeno'
