apiVersion: v1
kind: ConfigMap
data:
  gobmp.yaml: |
metadata:
  name: gobmp-config
  namespace: jalapeno
---
apiVersion: v1
kind: Secret
metadata:
  name: jalapeno
  namespace: jalapeno
data:
  .username: cm9vdA==
  .password: amFsYXBlbm8=
---
apiVersion: v1
kind: Service
spec:
  ports:
   - name: 5000-tcp
     nodePort: 30511
     port: 5000
     protocol: TCP
     targetPort: 5000
   - name: perf
     nodePort: 30767
     port: 56767
     protocol: TCP
     targetPort: 56767
  selector:
    app: topology-aio
  type: NodePort
metadata:
  name: topology-aio
  namespace: jalapeno
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology-aio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology-aio
  template:
    metadata:
      labels:
        app: topology-aio
    spec:
      initContainers:
        - name: arango-tester
          image: yauritux/busybox-curl
          command: ["sh", "-c", "until [ $(curl -s -I -o /dev/null -w '%{response_code}' --user 'root:jalapeno' -X GET http://arangodb:8529/_api/version) -eq 200 ]; do sleep 5; done"]
      containers:
        - args:
          - --v
          - "5"
          - --database-server
          - "http://arangodb:8529"
          - --database-name
          - "jalapeno"
        image: docker.io/iejalapeno/topology-aio:latest
        imagePullPolicy: Always
        name: topology-aio
        volumeMounts:
          - name: credentials
            mountPath: /credentials
        ports:
        - containerPort: 5000
          protocol: TCP
          name: 5000-tcp
        - containerPort: 56767
          protocol: TCP
          name: perf
      volumes:
        - name: config-volume
          configMap:
            name: gobmp-config
        - name: credentials
          secret:
            secretName: jalapeno
metadata:
  name: topology-aio
  namespace: jalapeno
