apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-egress-deployment
  namespace: jalapeno
  labels:
    app: telegraf-egress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-egress
  template:
    metadata:
      labels:
        app: telegraf-egress
    spec:
      containers:
        - name: telegraf
          image: telegraf:1.13-alpine
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-egress-config
              subPath: telegraf.conf
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: telegraf-egress-config
          configMap:
            name: telegraf-egress-config


