# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class D3Link(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, source: str=None, target: str=None, value: int=None):  # noqa: E501
        """D3Link - a model defined in Swagger

        :param source: The source of this D3Link.  # noqa: E501
        :type source: str
        :param target: The target of this D3Link.  # noqa: E501
        :type target: str
        :param value: The value of this D3Link.  # noqa: E501
        :type value: int
        """
        self.swagger_types = {
            'source': str,
            'target': str,
            'value': int
        }

        self.attribute_map = {
            'source': 'source',
            'target': 'target',
            'value': 'value'
        }

        self._source = source
        self._target = target
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'D3Link':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The d3Link of this D3Link.  # noqa: E501
        :rtype: D3Link
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source(self) -> str:
        """Gets the source of this D3Link.


        :return: The source of this D3Link.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this D3Link.


        :param source: The source of this D3Link.
        :type source: str
        """

        self._source = source

    @property
    def target(self) -> str:
        """Gets the target of this D3Link.


        :return: The target of this D3Link.
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target: str):
        """Sets the target of this D3Link.


        :param target: The target of this D3Link.
        :type target: str
        """

        self._target = target

    @property
    def value(self) -> int:
        """Gets the value of this D3Link.


        :return: The value of this D3Link.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this D3Link.


        :param value: The value of this D3Link.
        :type value: int
        """

        self._value = value
