# coding: utf-8

"""
    Voltron Framework

    This outlines version 1 of the voltron framework API. 

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class LinkEdge(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, key=None, _from=None, to=None, from_ip=None, to_ip=None, netmask=None, label=None, v6=None):
        """
        LinkEdge - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'key': 'str',
            '_from': 'str',
            'to': 'str',
            'from_ip': 'str',
            'to_ip': 'str',
            'netmask': 'str',
            'label': 'str',
            'v6': 'bool'
        }

        self.attribute_map = {
            'key': '_key',
            '_from': '_from',
            'to': '_to',
            'from_ip': 'FromIP',
            'to_ip': 'ToIP',
            'netmask': 'Netmask',
            'label': 'Label',
            'v6': 'V6'
        }

        self._key = key
        self.__from = _from
        self._to = to
        self._from_ip = from_ip
        self._to_ip = to_ip
        self._netmask = netmask
        self._label = label
        self._v6 = v6

    @property
    def key(self):
        """
        Gets the key of this LinkEdge.

        :return: The key of this LinkEdge.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """
        Sets the key of this LinkEdge.

        :param key: The key of this LinkEdge.
        :type: str
        """

        self._key = key

    @property
    def _from(self):
        """
        Gets the _from of this LinkEdge.

        :return: The _from of this LinkEdge.
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """
        Sets the _from of this LinkEdge.

        :param _from: The _from of this LinkEdge.
        :type: str
        """

        self.__from = _from

    @property
    def to(self):
        """
        Gets the to of this LinkEdge.

        :return: The to of this LinkEdge.
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """
        Sets the to of this LinkEdge.

        :param to: The to of this LinkEdge.
        :type: str
        """

        self._to = to

    @property
    def from_ip(self):
        """
        Gets the from_ip of this LinkEdge.

        :return: The from_ip of this LinkEdge.
        :rtype: str
        """
        return self._from_ip

    @from_ip.setter
    def from_ip(self, from_ip):
        """
        Sets the from_ip of this LinkEdge.

        :param from_ip: The from_ip of this LinkEdge.
        :type: str
        """

        self._from_ip = from_ip

    @property
    def to_ip(self):
        """
        Gets the to_ip of this LinkEdge.

        :return: The to_ip of this LinkEdge.
        :rtype: str
        """
        return self._to_ip

    @to_ip.setter
    def to_ip(self, to_ip):
        """
        Sets the to_ip of this LinkEdge.

        :param to_ip: The to_ip of this LinkEdge.
        :type: str
        """

        self._to_ip = to_ip

    @property
    def netmask(self):
        """
        Gets the netmask of this LinkEdge.

        :return: The netmask of this LinkEdge.
        :rtype: str
        """
        return self._netmask

    @netmask.setter
    def netmask(self, netmask):
        """
        Sets the netmask of this LinkEdge.

        :param netmask: The netmask of this LinkEdge.
        :type: str
        """

        self._netmask = netmask

    @property
    def label(self):
        """
        Gets the label of this LinkEdge.

        :return: The label of this LinkEdge.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """
        Sets the label of this LinkEdge.

        :param label: The label of this LinkEdge.
        :type: str
        """

        self._label = label

    @property
    def v6(self):
        """
        Gets the v6 of this LinkEdge.

        :return: The v6 of this LinkEdge.
        :rtype: bool
        """
        return self._v6

    @v6.setter
    def v6(self, v6):
        """
        Sets the v6 of this LinkEdge.

        :param v6: The v6 of this LinkEdge.
        :type: bool
        """

        self._v6 = v6

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, LinkEdge):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
