apiVersion: v1
kind: Service
metadata:
  name: influxdb-np
  namespace: voltron
  labels:
    app: influxdb
spec:
  ports:
    - name: 8086-tcp
      port: 8086
      nodePort: 30308
      targetPort: 8086
  type: NodePort
  selector:
    app: influxdb
