apiVersion: v1
kind: PersistentVolume
metadata:
   name: influxdb
spec:
  capacity:
       storage: 50Gi
  accessModes:
       - ReadWriteMany
  nfs:
    path: /data/openshift-nfs/influxdb
    server: 10.200.99.44
  persistentVolumeReclaimPolicy: Retain
