apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: voltron
  name: latency
  labels:
    app: latency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency
  template:
    metadata:
      labels:
        app: latency
    spec:
      containers:
      - name: latency
        image: dockerhub.cisco.com/gspie-docker-local/latency:1.0
        args:
          - --frameworkEndpoint
          - framework.voltron.svc.cluster.local:8876
          - --kafkaEndpoint
          - osc01.rio.wwva.ciscolabs.com:30902
