---
apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lslinknode-edge
  template:
    metadata:
      labels:
        app: lslinknode-edge
    spec:
      containers:
        - args:
            - --v
            - "6"
            - --message-server
            - "broker.jalapeno:9092"
            - --database-server
            - "http://arangodb.jalapeno:8529"
            - --database-name
            - "jalapeno"
          image: docker.io/iejalapeno/lslinknode-edge:latest
          imagePullPolicy: IfNotPresent
          name: lslinknode-edge
          volumeMounts:
            - name: credentials
              mountPath: /credentials
      volumes:
        - name: credentials
          secret:
            secretName: jalapeno
metadata:
  name: lslinknode-edge
  namespace: jalapeno
