---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pvzoo1
spec:
  capacity:
       storage: 10Gi
  accessModes:
       - ReadWriteOnce
  hostPath:
       path: "/var/lib/zookeeper"
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pvkafka
spec:
  capacity:
       storage: 50Gi
  accessModes:
       - ReadWriteOnce
  hostPath:
       path: "/var/lib/kafka/data"
