---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pvkafka
spec:
  capacity:
       storage: 50Gi
  accessModes:
       - ReadWriteMany
  nfs:
    path: /data/openshift-nfs/pvkafka
    server: 10.225.210.98
  persistentVolumeReclaimPolicy: Retain
