---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pvkafka
spec:
  capacity:
       storage: 50Gi
  accessModes:
       - ReadWriteMany
  nfs:
    path: /export/pvkafka
    server: 10.0.250.2
  persistentVolumeReclaimPolicy: Retain
