apiVersion: v1
kind: Service
metadata:
  name: zookeeper-np
  namespace: jalapeno
spec:
  ports:
  - name: 2181-tcp
    port: 2181
    nodePort: 30218
    targetPort: 2181
  type: NodePort
  selector:
    app: zookeeper
