apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: jalapeno
spec:
  ports:
  - port: 2888
    name: peer
  - port: 3888
    name: leader-election
  - port: 2181
    name: client
  clusterIP: None
  selector:
    app: zookeeper
    storage: persistent
