# coding: utf-8

"""
    Voltron Framework

    This outlines version 1 of the voltron framework API. 

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Router(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, key=None, name=None, router_ip=None, bgpid=None, is_local=None, asn=None):
        """
        Router - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'key': 'str',
            'name': 'str',
            'router_ip': 'str',
            'bgpid': 'str',
            'is_local': 'bool',
            'asn': 'str'
        }

        self.attribute_map = {
            'key': '_key',
            'name': '_name',
            'router_ip': 'RouterIP',
            'bgpid': 'BGPID',
            'is_local': 'IsLocal',
            'asn': 'ASN'
        }

        self._key = key
        self._name = name
        self._router_ip = router_ip
        self._bgpid = bgpid
        self._is_local = is_local
        self._asn = asn

    @property
    def key(self):
        """
        Gets the key of this Router.

        :return: The key of this Router.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """
        Sets the key of this Router.

        :param key: The key of this Router.
        :type: str
        """

        self._key = key

    @property
    def name(self):
        """
        Gets the name of this Router.

        :return: The name of this Router.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Router.

        :param name: The name of this Router.
        :type: str
        """

        self._name = name

    @property
    def router_ip(self):
        """
        Gets the router_ip of this Router.

        :return: The router_ip of this Router.
        :rtype: str
        """
        return self._router_ip

    @router_ip.setter
    def router_ip(self, router_ip):
        """
        Sets the router_ip of this Router.

        :param router_ip: The router_ip of this Router.
        :type: str
        """

        self._router_ip = router_ip

    @property
    def bgpid(self):
        """
        Gets the bgpid of this Router.

        :return: The bgpid of this Router.
        :rtype: str
        """
        return self._bgpid

    @bgpid.setter
    def bgpid(self, bgpid):
        """
        Sets the bgpid of this Router.

        :param bgpid: The bgpid of this Router.
        :type: str
        """

        self._bgpid = bgpid

    @property
    def is_local(self):
        """
        Gets the is_local of this Router.

        :return: The is_local of this Router.
        :rtype: bool
        """
        return self._is_local

    @is_local.setter
    def is_local(self, is_local):
        """
        Sets the is_local of this Router.

        :param is_local: The is_local of this Router.
        :type: bool
        """

        self._is_local = is_local

    @property
    def asn(self):
        """
        Gets the asn of this Router.

        :return: The asn of this Router.
        :rtype: str
        """
        return self._asn

    @asn.setter
    def asn(self, asn):
        """
        Sets the asn of this Router.

        :param asn: The asn of this Router.
        :type: str
        """

        self._asn = asn

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Router):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
