apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: openbmpd
  namespace: voltron
spec:
  serviceName: "openbmpd"
  replicas: 1
  template:
    metadata:
      labels:
        app: openbmpd
      annotations:
        openshift.io/scc: privileged
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: openbmpd
          image: openbmp/collector
          ports:
            - containerPort: 5005
              protocol: TCP
          env:
            - name: KAFKA_FQDN
              value: '10.128.0.56:9092'
          privileged: true
          runAsUser: 0
          resources: {}
          securityContext:
            privileged: true
            runAsUser: 0
