apiVersion: v1
kind: Service
metadata:
  name: openbmpd-np
  namespace: voltron
spec:
  ports:
  - name: 5000-tcp
    port: 5000
    nodePort: 30500
    targetPort: 5000
  type: NodePort
  selector:
    app: openbmpd
