apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: voltron
  name: portal
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: ievoltron/portal:0.0.1@sha256:ef67ac43459786577f4ba442badc3f06b991d476f03239e72b7fd6ab6a030980
        env:
        - name: FLASK_ENV
          value: production
        - name: API_NETLOC
          value: voltron-sjc.cisco.com:30880
        ports:
        - containerPort: 80
          protocol: TCP
