apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: voltron
  name: portal
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: ievoltron/portal:0.0.1@sha256:345bb5980af3f4c7bc24b9dc0a27286c7ad54d96f76fbaf6b159d572caf70050
        env:
        - name: FLASK_ENV
          value: production
        - name: API_NETLOC
          value: http://voltron-sjc.cisco.com:30881/
        ports:
        - containerPort: 80
          protocol: TCP
