apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: voltron
  name: portal
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: ievoltron/portal:0.0.1@sha256:76ff6e109a8538686689dea5787a3da17a91e7496efabf50a339f3c7321cc5be
        env:
        - name: FLASK_ENV
          value: production
        - name: API_NETLOC
          value: voltron-sjc.cisco.com:30881
        ports:
        - containerPort: 80
          protocol: TCP
