{{- if not .Values.global.storageClass }}
# PersistentVolume for ZooKeeper
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-zookeeper-pv
  labels:
    {{- include "jalapeno.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/zookeeper"
---
# PersistentVolume for Kafka
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-kafka-pv
  labels:
    {{- include "jalapeno.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/kafka/data"
---
# PersistentVolume for ArangoDB Data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-arangodb-data-pv
  labels:
    {{- include "jalapeno.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/arangodb/data"
---
# PersistentVolume for ArangoDB Apps
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-arangodb-apps-pv
  labels:
    {{- include "jalapeno.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/arangodb/apps"
---
# PersistentVolume for InfluxDB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-influxdb-pv
  labels:
    {{- include "jalapeno.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/influxdb"
---
# PersistentVolume for Grafana
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-grafana-pv
  labels:
    {{- include "jalapeno.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/grafana"
{{- end }} 