apiVersion: v1
kind: PersistentVolume
metadata:
   name: arangodb-apps
spec:
  capacity:
       storage: 10Gi
  accessModes:
       - ReadWriteMany
  hostPath:
       path: /var/lib/arangodb3-apps
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: arangodb
spec:
  capacity:
       storage: 50Gi
  accessModes:
       - ReadWriteMany
  hostPath:
       path: /var/lib/arangodb3
  persistentVolumeReclaimPolicy: Retain
