apiVersion: v1
kind: PersistentVolume
metadata:
   name: arangodb
spec:
  capacity:
       storage: 50Gi
  accessModes:
       - ReadWriteMany
  nfs:
    path: /export/arangodb
    server: 10.0.250.2
  persistentVolumeReclaimPolicy: Retain