---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology
  template:
    metadata:
      labels:
        app: topology
    spec:
      containers:
        - args:
          - --v
          - "5"
          - --message-server
          - "broker.jalapeno:9092"
          - --database-server
          - "http://arangodb.jalapeno:8529"
          - --database-name
          - "jalapeno"
          - --database-user
          - "root"
          - --database-pass
          - "jalapeno"
          image: docker.io/iejalapeno/topology@sha256:93a92a442a7d5fc7dfbeda5a54d50203e5cc1cdc8585ee0d86cf9ce808f9e11e 
          imagePullPolicy: Always
          name: topology
metadata:
  name: topology
  namespace: jalapeno
