apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: jalapeno
data:
  grafana.ini: |-
    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins

    [log]
    # Either "console", "file", "syslog". Default is console and  file
    # Use space to separate multiple modes, e.g. "console file"
    mode = console

    [security]
    # default admin user, created on startup
    admin_user = root
    admin_password = jalapeno
