apiVersion: v1
kind: Service
metadata:
  name: grafana-np
  namespace: voltron
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    nodePort: 30300
    targetPort: 3000
  type: NodePort
  selector:
    app: grafana
