apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: epe-edges-collector
  namespace: jalapeno
  labels:
    app: epe-edges-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epe-edges-collector
  template:
    metadata:
      labels:
        app: epe-edges-collector
    spec:
      containers:
      - name: epe-edges
        image: iejalapeno/epe-edges:2.0@sha256:0142fc4806d2e7e871fe5599ab7dd42463149fc8340dd6e321c0e7338d4902e2
