apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mdt-pipeline-deployment
  labels:
    app: mdt-stack-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdt-stack-pipeline
  template:
    metadata:
      labels:
        app: mdt-stack-pipeline
    spec:
      containers:
      - name: mdt-pipeline
        image: ievoltron/pipeline:v0.1.13@sha256:9cb8bb29c01423efd700b66e7014bf2efa207453ef16fbcbe709b31c284887bb
        volumeMounts:
        - mountPath: /data
          name: mdt-pipeline-data
        - mountPath: /data/config
          name: mdt-pipeline-data-config
      volumes:
      - name: mdt-pipeline-data
        emptyDir: {}
      - name: mdt-pipeline-data-config
        configMap:
          defaultMode: 420
          name: mdt-pipeline-config
