apiVersion: apps/v1
kind: Deployment
metadata:
  name: rt-processor
  namespace: jalapeno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rt-processor
  template:
    metadata:
      labels:
        app: rt-processor
    spec:
      containers:
        - args:
          - --v
          - "5"
          image: docker.io/iejalapeno/rt-processor@sha256:300e7ac7f0047cea45c16198419974831d8e84fa11a7a99849882f7a084d799f
          imagePullPolicy: Always
          name: rt-processor
