name: Arango Smoke Test
on:
  workflow_run:
    workflows: [Minimal Jalapeno Spinup]
    types: [completed]

jobs:
  Kill-XRD:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Kill XRD testbed
        run: |
          cd ${{ github.workspace }}/build/tools/xrd
          docker-compose down

  Run-XRD:
    needs: Kill-XRD
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run XRD testbed
        run: |
          cd ${{ github.workspace }}/build/tools/xrd
          docker-compose up -d

  Check-Arango:
    needs: Run-XRD
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check Arango for routes
        run: |
          cd ${{ github.workspace }}/build/tools
          ./check_arango.sh
