---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pvzoo
spec:
  capacity:
       storage: 10Gi
  accessModes:
       - ReadWriteMany
  nfs:
    path: /export/pvzoo
    server: {{ host_ip }}
  persistentVolumeReclaimPolicy: Retain
